[package]
name = "goofy-bbs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
cursive = { version = "0.21.1", features = ["termion-backend"] }
# posix-acl = "1.2.0"
rusqlite = "0.32.1"

[features]
shell = []
sudo-shell = ["shell"]
